postprocessor_pipeline: # set by postprocessor_pipeline_name

   #  Delete layers that are not needed.
   #  - name: delete_original_layers
   #    type: gridMapFilters/DeletionFilter
   #    params:
   #      layers: [lowest_scan_point,sensor_x_at_lowest_scan, sensor_y_at_lowest_scan, sensor_z_at_lowest_scan] # List of layers.

  # Fill holes in the map with inpainting.
   - name: inpaint
     type: gridMapCv/InpaintFilter
     params:
       input_layer: elevation
       output_layer: inpaint
       radius: 0.05

  # Reduce noise with a radial blurring filter.
  #  - name: mean_in_radius
  #    type: gridMapFilters/MeanInRadiusFilter
  #    params:
  #      input_layer: inpaint
  #      output_layer: elevation_smooth
  #      radius: 0.2

