robot_name: 'go2'

joint_names: &jn ["LF_HAA", "LF_HFE", "LF_KFE", "LH_HAA", "LH_HFE", "LH_KFE", "RF_HAA", "RF_HFE", "RF_KFE", "RH_HAA", "RH_HFE", "RH_KFE"]
base_name: "base"

state_topic: "anymal_d/state"
command_topic: "anymal_d/command"
change_controller_topic: "anymal_d/change_controller"
contact_topics: ["/lf_foot_contact", "/rf_foot_contact", "/lh_foot_contact","/rh_foot_contact"] 

static_controller:
  stand_controller:
    joint_angles: [0.0, 0.806, -1.802, 0.0, 0.996, -1.802, 0.0, 0.806, -1.802, 0.0, 0.996, -1.802] # LF, LH, RF, RH
  sit_controller:
    joint_angles: [0.0, 1.36, -2.55, 0.0, 1.36, -2.55, 0.0, 1.36, -2.55, 0.0, 1.36, -2.55] # LF, LH, RF, RH
  kp: 90
  kd: 0.5
  interpolation_time: 1.8 # s
  rate: 50 # Hz

mpc_controller:
  wbc_type: "sqp"
  reference_trajectory:
    terrain_topic: "/convex_plane_decomposition_ros/filtered_map"
    reference_topic: "/anymal_mpc_target"
    observation_topic: "/anymal_mpc_observation"
    traj_dt: 0.1
    traj_knots: 10
    blind: false

anymal_d:
  joint_controller:
      type: tbai_ros_gazebo/JointController
      joints: *jn

reference_generator:
  type: "twist"

  joystick:
    topic: "joy"
    ramped_velocity: 5.0
    x_index: 1
    y_index: 0
    yaw_index: 3
    x_scale: 1.0
    y_scale: 0.5
    yaw_scale: 0.5

  twist:
    topic: "cmd_vel"

estimator_type: "muse"

gazebo:
  contact_sensor:
    enabled: true
    update_rate: 200 # Hz

  ground_truth_state_publisher:
    enabled: false
    update_rate: 400 # Hz

  muse_state_publisher:
    enabled: true
    update_rate: 200 # Hz